#ifndef token_h
#define token_h

#include <stdlib.h>
#include <string.h>

typedef enum Token {
	DESCONHECIDO = -1,
	IF_TOKEN = 258,
	ELSE_IF_TOKEN = 259,
	ELSE_TO

} Token;

typedef enum TipoOperador{
	DESCONHECIDO = -1,
	RELACIONAL_IGUALDADE,
	RELACIONAL_NEGACAO,
	RELACIONAL_MAIORQUE,
	RELACIONAL_MENORQUE,
	RELACIONAL_MAIORIGUAL,
	RELACIONAL_MENORIGUAL,
	RELACIONAL_OR,
	RELACIONAL_AND,

	MATEMATICO_SOMA,
	MATEMATICO_SUBTRACAO,
	MATEMATICO_MULTIPLICACAO,
	MATEMATICO_DIVISAO,
	MATEMATICO_MOD,
	MATEMATICO_POW,
	MATEMATICO_INCREMENTO,
	MATEMATICO_DECREMENTO
} TipoOperador;


typedef enum TipoToken {
	UNKNOWN_TYPE = -1,
	INT_TYPE,
	FLOAT_TYPE,
	CHAR_TYPE,
	STRING_TYPE,
	BOOLEAN_TYPE,
	VECTOR_TYPE,
	DATE_TYPE
} IDType;

#endif